---
- name: stop all guests
  hosts: vm_fusion_host
  remote_user: mamurai
  group_vars: ../group_vars/vm_fusion_host

  tasks:
    - name: shutdown each guests
      shell: /Applications/VMware\ Fusion.app/Contents/Public/vmrun -T ws stop {{ item.vmx }} 
      with_items: "{{ vm_guests }}"

    - name : Wait shutdown guests
      shell: /Applications/VMware\ Fusion.app/Contents/Public/vmrun -T ws list | grep {{ item.vmx }}
      failed_when: False
      register: result
      until: result.rc != 0
      retries: 10
      delay: 10
      with_items: "{{ vm_guests }}"
