---
- name: Launch instance
  ec2:
     aws_access_key: "{{ec2_access_key}}"
     aws_secret_key: "{{ec2_secret_key}}"
     key_name: "{{ keypair }}"
     group_id: "{{ security_group_id }}"
     instance_type: "{{ instance_type }}"
     instance_tags:
       TowerManaged: True
     image: "{{ image }}"
     wait: true
     region: "{{ region }}"
     vpc_subnet_id: "{{ subnet_id }}"
     assign_public_ip: yes
     count: "{{ ins_count }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
